services:
  neon-local:
    image: neondatabase/neon_local:latest
    container_name: neon-local
    ports:
      - '55432:5432'
    env_file:
      - .env.development

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    env_file:
      - .env.development
    environment:
      NODE_ENV: development
      PORT: 3000
      NEON_LOCAL: 'true'
      NEON_LOCAL_ENDPOINT: http://neon-local:5432/sql
      DATABASE_URL: postgres://neon:npg@neon-local:5432/dbname?sslmode=require
      ARCJET_KEY: ${ARCJET_KEY}
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
      - ./drizzle:/app/drizzle
      - ./drizzle.config.js:/app/drizzle.config.js
      - /app/node_modules
    depends_on:
      - neon-local
